# Generated by Django 4.0.3 on 2022-03-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NFT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField(default='none')),
                ('name', models.CharField(max_length=32)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('offer', models.BooleanField(default=False)),
                ('offer_price', models.IntegerField(default=0)),
                ('owner', models.CharField(blank=True, max_length=64, null=True)),
                ('blockchain', models.CharField(default='Ethereum', max_length=16)),
                ('collection', models.CharField(blank=True, max_length=32, null=True)),
                ('properties', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField(default='none')),
                ('fname', models.CharField(max_length=32)),
                ('lname', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=50)),
                ('collection', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.CharField(blank=True, max_length=200, null=True)),
                ('favorited', models.CharField(blank=True, max_length=200, null=True)),
                ('offers', models.CharField(blank=True, max_length=200, null=True)),
                ('properties', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
