# Generated by Django 4.0.3 on 2022-03-16 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft_Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='properties',
            field=models.TextField(),
        ),
    ]
