# Generated by Django 4.0.3 on 2022-03-17 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nft_Api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='properties',
            new_name='bio',
        ),
    ]
