# Generated by Django 4.0.3 on 2022-03-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft_Api', '0002_nft_blockchain_nft_collection_nft_offer_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='collection',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='offers',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='properties',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
