# Generated by Django 4.0.3 on 2022-03-17 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nft_Api', '0003_alter_user_collection_alter_user_offers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='properties',
            new_name='bio',
        ),
    ]
