# Generated by Django 4.0.3 on 2022-03-17 15:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft_Api', '0005_remove_user_bio_user_properties_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='collection',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='offers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
