# Generated by Django 4.0.3 on 2022-03-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft_Api', '0006_alter_user_collection_alter_user_offers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='collection',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='offers',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
