# Generated by Django 4.0.3 on 2022-03-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft_Api', '0008_remove_user_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='properties',
            field=models.TextField(blank=True, null=True),
        ),
    ]
