# Generated by Django 4.0.3 on 2022-03-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft_Api', '0009_user_properties'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='collection',
            new_name='collected',
        ),
        migrations.AddField(
            model_name='user',
            name='created',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='favorited',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
