# Generated by Django 4.0.3 on 2022-03-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft_Api', '0010_rename_collection_user_collected_user_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='collected',
        ),
        migrations.AddField(
            model_name='user',
            name='collection',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
