# Generated by Django 4.0.3 on 2022-03-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft_Api', '0012_remove_user_properties_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.AddField(
            model_name='user',
            name='properties',
            field=models.TextField(blank=True, null=True),
        ),
    ]
