# Generated by Django 4.0.3 on 2022-03-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft_Api', '0013_remove_user_bio_user_properties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nft',
            name='owner',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='nft',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
